simplify tests
The start/stop tests fail with:
Error: Cannot open an HTTP server: socket.error reported AF_UNIX path too long

Hence, I have replaced them with simple command invocations